# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  create:
    tags:

jobs:

  release:
    name: create-release

    runs-on: ubuntu-latest
    steps:
    - name: Release
      uses: softprops/action-gh-release@v1

  build:
    needs:
      - release
    name: build for ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            asset_name: analyser-linux
            compress_name: analyser-linux
          - os: windows-latest
            asset_name: analyser-windows
            compress_name: analyser-windows
          - os: macos-11
            asset_name: analyser-macos
            compress_name: analyser-macos.app
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
        
    - name: Build with Maven
      run: mvn javafx:jlink

    - name: package
      working-directory: target
      run: jpackage --runtime-image image --type app-image -n ${{ matrix.asset_name }} -m indi.zhenyue.networkanalyser/indi.zhenyue.networkanalyser.Launcher

    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
          type: 'tar'
          filename: '${{ matrix.asset_name }}.tar.gz'
          path: ${{ matrix.compress_name }}
          directory: target

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
          name: ${{ matrix.asset_name }}
          path: target/${{ matrix.asset_name }}.tar.gz

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/${{ matrix.asset_name }}.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
