# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  create:
    tags:

jobs:
  build:
    name: build for ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            asset_name: analyser-linux-amd64
          - os: windows-latest
            asset_name: analyser-windows-amd64
          - os: macos-11
            asset_name: analyser-macos-amd64
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
        
    - name: Build with Maven
      run: mvn javafx:jlink

    - name: package
      working-directory: target
      run: jpackage --runtime-image image --type app-image -n ${{ matrix.asset_name }} -m indi.zhenyue.networkanalyser/indi.zhenyue.networkanalyser.Launcher

    - name: Archive Release
      uses: thedoctor0/zip-release@master
      if: ${{ runner.os != 'macOS' }}
      with:
          type: 'tar'
          filename: '${{ matrix.asset_name }}.tar.gz'
          path: ${{ matrix.asset_name }}
          directory: target

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
          name: ${{ matrix.asset_name }}
          path: target/${{ matrix.asset_name }}.tar.gz



    - name: Release
      if: ${{ runner.os != 'macOS' }}
      uses: softprops/action-gh-release@v1
      with:
        files: target/${{ matrix.asset_name }}.tar.gz

    - name: Release mac
      if: ${{ runner.os == 'macOS' }}
      uses: softprops/action-gh-release@v1
      with:
          files: target/${{ matrix.asset_name }}